[package]
name = "zhashgen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2"
rayon = "1"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
crc32fast = "1"
md5 = "0.8.0"
indicatif = "0.17"
num_cpus = "1.16"
